snyk/policy

lib/index.js, test/fixtures/ignore-duped/.snyk, test/fixtures/ignore-duped/package.json, test/fixtures/ignore/.snyk, test/functional/SC-1084.test.js, test/unit/policy-save.test.js
Fixes the issue where two ignore rules with the same vuln.id cause an exception. 
`lib/index.js` - have included inline comment to explain change.
https://snyksec.atlassian.net/browse/SC-1084
=> fix: merging ignore policies with same id

lib/filter/ignore.js, lib/filter/patch.js, test/unit/filter-ignore.test.js, test/unit/filter-patch.test.js
Returns information about filtered vulns from the `filter` method.
This is a non breaking change as filtered vulns were already returned as an array at `vulns.filtered`. But now each vuln that was filtered will contain a key `ignore` if the policy file states that it should be ignored, and `patch` if the policy file states that it was patched.
The value of the `ignore` key is as follows:
```javascript
[
{
'sqlite > sqlite3 > node-pre-gyp > request > hawk': {
reason: 'hawk got bumped',
expires: '2116-03-01T14:30:04.136Z'
}
}
]
```
This means that the vuln was ignored at the path `sqlite > sqlite3 > node-pre-gyp > request > hawk`.
The value of the `patch` key is as follows:
```javascript
[
{
'jade > transformers > uglify-js': {
patched: '2016-03-03T18:06:06.091Z'
}
}
]
```
This means that …
=> feat: return information about why vulns were filtered

lib/parser/index.js, test/unit/parser.test.js
Handles invalid inputs to `policy.import` which would get parsed by `yaml.safeLoad` into a `string` or `number`. We only support `object`s for our policy files.
If an invalid input is provided, we handle it the same way for no input provided (return a blank policy definition)
```bash
tap test/unit/parser.test.js
```
Try calling `parser. loadFromText('test')` or `parser. loadFromText('1')`. Expect the following response:
```javascript
{
version: 'v1.0.0',
ignore: {},
patch: {},
}
```
https://sentry.io/snyk/phoenix_prod/issues/171767999/
=> fix: make parser.import handle invalid inputs

lib/parser/add-comments.js, lib/parser/index.js, test/fixtures/ignore/.snyk, test/unit/parser-add-comments.test.js, test/unit/policy-save.test.js
Adds comments to policy files
E.g.
```yaml
version: v1.6.1
ignore:
'npm:hawk:20160119':
- sqlite > sqlite3 > node-pre-gyp > request > hawk:
reason: hawk got bumped
expires: '2116-03-01T14:30:04.136Z'
```
`tap test/unit/policy-save.test.js`
- Go to any repo that has vulns and run `snyk wizard`
- Answer the questions so that a policy file is created/modified (patch or ignore some vulns)
- Ensure that the generated policy file contains comments inline
This will help with onboarding new users who have never seen a Snyk policy file before and want to understand it's purpose
=> feat: add comments to policy files

package.json
Bumps the `snyk-module` dependency to `^1.8.1`. This allows the policy to be applied to projects whose `name` does not conform to npmjs standards. This prevents projects from being published on npmjs.com, but nothing else. We encounter such projects quite often and want to be able to apply snyk policy on them.
=> fix: bump snyk-module to remove npmjs name validation

lib/filter/ignore.js
Instead of inferring upgradability & patchability, use the booleans `isUpgradable` and `isPatchable` which are the source of truth.
Find an issue that is not upgradable or patchable (but may have an upgrade path regardless). 
Ignore the issue via the API/website with `disregardIfFixable` to true. Make sure that the issue is ignored.
Sometimes there is an upgrade path that cannot be applied within the project. In this case there may be an upgrade path, but `isUpgradable` will still be false.
=> fix: use isUpgradable, isPatchable booleans for disregardIfFixable

lib/filter/ignore.js, test/unit/filter-ignore.test.js
Returns the original path that was matched when a vuln is filtered due to an ignore rule.
```bash
tap test/unit/filter-ignore.test.js
```
Filter a list of vulns where one or more has an ignore policy that is applicative. Ensure that the `filtered` array contains the path(s) within the `vuln.filtered.ignored` array of applicative ignore rules.
This is needed so that we can display the matched path within the reporting service. Currently this information is lost to us when we look at the `filtered` metadata of a `vuln`.
=> feat: return path for ignored issues

lib/filter/patch.js, lib/index.js, test/fixtures/patch/.snyk, test/functional/load-multi.test.js, test/unit/filter-patch.test.js, test/unit/policy.test.js
For some reason some of the patch policies have an empty body.
We should coerce this to an empty object so that we can state the original path that the patch was applied via.
=> fix: handle patch policies with no body

lib/parser/v1.js, test/functional/BST-264.test.js
Remove patch from parsing result if it's broken for one of vulns.
* This PR fixing previous one.
https://github.com/snyk/policy/pull/25
https://snyksec.atlassian.net/browse/BST-264
=> fix: remove broken patch from parsing result

.npmrc, lib/filter/get-vuln-source.js, lib/match.js, package.json
Bump snyk-module, which now exports a function.
Additionally:
feat: remove @* logic so we hit the fast path
This @* logic is not helpful here, because snyk-module already
returns '*' for unrecognised versions.
It is incorrect, because we don't append the start for scoped
packages, as we are incorrectly checking for an @. i.e.
@snyk/foo matches, and it shouldn't.
It also stops us hitting the new fast-path in snyk-module.
=> feat: upgrade snyk-module and remove @*

lib/filter/ignore.js, lib/filter/notes.js, lib/index.js, package.json
Make sure we're not doing any extra work when `debug` logging is disabled.
=> fix: upgrade debug and skip some logging

test/fixtures/patch-with-git-url.json
Update fixtures to point to the correct location of our patch urls
=> chore: Update fixtures to correct patch urls

package.json
The major version bump here is about dropping node 6 support, which is fine.
=> feat: bump snyk-module (no more node 6)

lib/index.js, package.json, test/unit/get-by-vuln.test.js, test/unit/policy-save.test.js, test/unit/policy.test.js
then-fs monkey patches the stdlib, which causes problems for jest, c.f. https://github.com/facebook/jest/pull/8331
promise-fs is a drop-in replacement here, for us.
=> feat: swap out then-fs for promise-fs

package.json
We're trying to shake then-fs out of the tree here, and one of our
deps in our tree had a major version bump, which we must adopt here.
The major version bump comes with a node baseline change, which we are assuming we're okay with here.
=> feat: bump snyk deps to pick up then-fs drops

lib/filter/ignore.js, test/fixtures/ignore-security-policy/.snyk, test/fixtures/ignore-security-policy/package.json, test/fixtures/ignore-security-policy/parsed.json, test/fixtures/ignore-security-policy/vulns-incomplete-security-metadata.json, test/fixtures/ignore-security-policy/vulns-security-metadata.json, test/fixtures/ignore-security-policy/vulns.json, test/unit/filter-ignore.test.js
Implementing new source of ignore data from security policies.
In case issue was enriched with `securityPolicyMetaData.ignore` this issue should apply ignore from security policy only and skip other ignores. Also ignore object will contain few more fields and will look like:
```js
'npm:tar:20151103': [
{
reason: '',
reasonType: 'wont-fix',
source: 'security-policy',
ignoredBy: {
id: '22A6B3BE-ABEF-4407-A634-AB1BE30A552F',
name: 'Ignored by Security Policy',
},
created: '2021-06-13T09:33:57.318Z',
disregardIfFixable: false,
path: ['*'],
},
]
```
In other case old logic should be applied.
1. Checkout this branch locally and use it as local source for `snyk-policy` in registry
2. Enable ignore action FF in registry
3. Create new policy with the ignore action
4. Re-test project from the org …
=> feat: support security policies ignore action

lib/filter/ignore.js, lib/filter/index.js, lib/index.js, lib/match.js, test/fixtures/ignore-exact/.snyk, test/unit/filter-ignore.test.js, test/unit/match.test.js
Add a flag to the `ignore` method signature to opt-in to "simple"
path-matching behaviour.
The following vulnerability path: `['foo', 'bar', 'baz']` will be
matched by the following ignore rules under this behaviour:
- 'foo > bar > baz'
- 'foo > *'
- '*'
Under the default matching behaviour, there are some quirks that appear
specific to package manager use cases:
- The first element of vulnerabilities paths is sliced off
- If the path (minus the first element) "contains" the rule as a
substring, it will match. For example: the rule `file.json` will match
the path `["dir/file.json"]`.
- Attempts to parse paths as packages, URLs, or git objects.
The Snyk infrastructure-as-code use-case breaks under these default
behaviours, but we still want to use the policy library in order to not …
=> feat: optional "exact" ignore behaviour

lib/index.js, lib/parser/index.js
This PR is triggered by a work on Snyk CLI and its bundling with Webpack snyk/snyk#2105. Webpack can't resolve the dynamic require we are using here. Switched to a top-level require, as `version()` is called on top-level as well.
Also removed the self-execution functionality using module.parent. This was producing an empty console.log in some scenarios. Library is also not used self-executing/cli context
=> Make snyk-policy webpack compatible

.circleci/config.yml
Updates the Node Version in Circle CI configurations. That is because the Semantic version does not support versions lower than as described in errors.
```
npx: installed 522 in 10.004s
[semantic-release]: node version >=16 || ^14.17 is required. Found v12.22.1.
```
=> chore: update node version to latest of each

lib/parser/demunge.js, test/fixtures/parsed.json, test/unit/parser.test.js
- include the 'exclude' rules in the demunge implementation
- exclude might contain 2 categories/ids: global and code
- the entries for exclude.global/code might be simple paths (strings) or objects (including metadata like reason, creation/expiration dates).
=> feat: demunge 'exclude' rules

.circleci/config.yml
Updates the CircleCI config to always scan changes to main and report the results to Snyk. Previously, if you fixed an issue, it would not be reflected in Snyk until the following day (after the recurring tests have run). Unfortunately, CircleCI only allows parameters and conditions in certain places which made it a bit messy to conditionally report results to Snyk. This logic was implemented in an inline orb which allows us to namespace and parameterize commands for easier syncing between projects
[Jira ticket NARW-1307](https://snyksec.atlassian.net/browse/NARW-1307)
=> chore: report all vulns on master

.snyk, lib/filter/patch.js, package.json, test/functional/severity-control.test.js
Bump all dev dependencies to the latest version
- `@commitlint/cli` from 12.1.4 to 17.6.1
- `eslint` from 5.0.0 to 8.38.0
- needed to add a comment for a squashed exception
- `eslint-config-prettier` from 5.0.0 to 8.8.0
- `sinon` from 4.0.0 to 15.0.4
- `tap` from 12.0.1 to 16.3.4
- tests are now run synchronously unless a promise is returned
- added coverage thresholds. Coverage checks are now on by default
=> chore: bump dev deps

test/functional/BST-264.test.js, test/functional/SC-1026.test.js, test/functional/severity-control.test.js, test/unit/add-exclude.test.js, test/unit/add.test.js, test/unit/filter-ignore.test.js, test/unit/filter-patch.test.js, test/unit/filter.test.js, test/unit/get-by-vuln.test.js, test/unit/ignore-policy.test.js, test/unit/parser.test.js, test/unit/policy-args.test.js, test/unit/policy-parse.test.js, test/unit/policy.test.js
Replace deprecated Tap asserts:
- `t.deepEqual` to `t.same`
- `t.isa` to `t.type`
- `t.notEqual` to `t.not`
- `t.equals` to `t.equal`
`npm run test`
=> chore: update Tap asserts

lib/filter/get-vuln-source.js, lib/filter/patch.js, lib/index.js, package.json, test/unit/get-by-vuln.test.js, test/unit/policy-save.test.js, test/unit/policy.test.js
Remove [promise-fs](https://github.com/octet-stream/promise-fs) in favour of [fs/promises](https://nodejs.org/dist/latest-v10.x/docs/api/fs.html#fs_fs_promises_api). `fs/promises` was released in Node v10 (2018) and [promise-fs](https://github.com/octet-stream/promise-fs) has been deprecated for about 4 years. We were using both in the codebase
`npm run test`
and/or
`npm link` then `npm link snyk-policy` in Registry before running tests in Registry
=> fix: migrate from `promise-fs` to `fs/promises`

package.json, test/unit/filter-patch.test.js, test/unit/policy-save.test.js
Removes `proxyquire` in favour of `sinon.stub` for stubbing functionality during testing. We're already using `sinon` and `proxyquire` does not play nice with ESM
`npm run test`
=> chore: remove proxyquire

lib/parser/index.ts
Previously, the policy file version defaulted to the current version of the library.
Manually bump the `version` in `package.json` to `3.0.0` and run `npm pack`
Run `npm install <policyRepoPath>/snyk-policy-3.0.0.tgz` in Registry before running `npm run test`
=> fix: default policy file version to `v1`

.circleci/config.yml, package.json, test/functional/BST-264.test.ts, test/functional/SC-1026.test.ts, test/functional/SC-1084.test.ts, test/functional/append.test.ts, test/functional/load-multi.test.ts, test/functional/load-policies.test.ts, test/functional/severity-control.test.ts, test/unit/add-exclude.test.ts, test/unit/add.test.ts, test/unit/filter-expired.test.ts, test/unit/filter-ignore.test.ts, test/unit/filter-notes.test.ts, test/unit/filter-patch.test.ts, test/unit/filter.test.ts, test/unit/get-by-vuln.test.ts, test/unit/ignore-policy.test.ts, test/unit/match.test.ts, test/unit/old-format.test.ts, test/unit/parser-add-comments.test.ts, test/unit/parser.test.ts, test/unit/policy-args.test.ts, test/unit/policy-parse.test.ts, test/unit/policy-save.test.ts, test/unit/policy.test.ts, vitest.config.ts
Switches from [TAP](https://node-tap.org/) to [vitest](https://vitest.dev/) and replaces [sinon](https://sinonjs.org/) for vitest mocking
TAP was simply way too slow clocking in at around 28 sec (see below), whereas vitest runs in just over 5 sec for the full suite. vitest also has much better editor integration (last image) with seamless debugging
Note: the way that tests are aggregated does differ, but all tests have been ported
`npm run test`
Old, slow test run with TAP 🐢 
New, fast test run with vitest! 🚀 
Editor integration
=> chore: switch to vitest

lib/parser/index.ts, test/unit/parser.test.ts
Defaults to an empty policy file when an array is passed in.
Currently, we have a customer passing in a YAML array (below) as a policy file and the policy library is not handling it gracefully
```
- object Object
```
https://snyksec.atlassian.net/browse/NARW-2055
=> fix: default to an empty policy when an YAML array is passed in for the policy file

lib/index.ts, lib/parser/index.ts, test/unit/policy-save.test.ts
Saves policies with the latest schema version.
The policy schema version was coupled to the library version. When we bumped the library to v2 for a potentially breaking change to the library (but no changes to the schema), the library started looking for a non-existent v2 parser.
In #106 we decoupled the default schema version from the library version for reading policies, but files were still be written with the library's latest version. Which again, resulting in the library looking for a v2 parser
This was caught during the [integration tests in Registry](https://app.circleci.com/pipelines/github/snyk/registry/240428/workflows/b5a96f96-03e7-4955-b367-68bc7418d22c/jobs/1134697)
- Load a policy with any verion
- Save the policy (should be saved with latest schema version)
- Then try to …
=> fix: save policies with the latest schema version

.circleci/config.yml
The `snyksec` Github service account [is being disabled](https://snyk.slack.com/archives/C017V2JPKNX/p1683551183603779) to comply with the [ProdSec security standards](https://potential-adventure-z7gm728.pages.github.io/standards/standard_for_circleci_secrets_usage.html), so each team must create their own Github service account. The Narwhal service account can be found in the `Team Narwhal` 1Password vault.
Further, as per the standards, secrets and contexts should not be shared across projects where possible to limit the blast radius. So, as part of this work, a `narwhal-policy` CircleCI context has been created with a project specific `SNYK_TOKEN` and `GITHUB_PRIVATE_TOKEN`. This PR updates the context, after which, the `SNYK_TOKEN` environment variable will be removed from CircleCI
=> chore: update CircleCI context

package.json, tsconfig.json, types/snyk-resolve.d.ts, types/snyk-try-require.d.ts
Types the following dependencies either by installing the type if available or creating a custom type declaration file
- [debug](https://github.com/debug-js/debug)
- [js-yaml](https://github.com/nodeca/js-yaml)
- [lodash.clonedeep](https://github.com/lodash/lodash)
- [snyk-resolve](https://github.com/snyk/resolve-package)
- [snyk-try-require](https://github.com/Snyk/try-require)
Note: this also limits the version range of typescript to only minor updates and the latest `5.1.x` versions are causing OOM errors when linting. More info [here](https://github.com/microsoft/TypeScript/issues/53087)
=> chore: type library dependencies

test/functional/SC-1026.test.ts, test/functional/severity-control.test.ts, test/unit/add-exclude.test.ts, test/unit/filter-ignore.test.ts, test/unit/filter-notes.test.ts, test/unit/filter-patch.test.ts, test/unit/get-by-vuln.test.ts, test/unit/helpers.ts, test/unit/match.test.ts, test/unit/policy-args.test.ts, test/unit/policy-parse.test.ts, test/unit/policy.test.ts, test/unit/types.test.ts, tsconfig.json
Types all of the test files and turns strict type checking on. This PR should not change any logic
[NARW-2131](https://snyksec.atlassian.net/browse/NARW-2131)
[NARW-2131]: https://snyksec.atlassian.net/browse/NARW-2131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: turn strict type checking on

lib/parser/v1.ts, test/unit/filter-empty-rule.test.ts
`policy.filter` no longer throws an error when the policy file contains empty rulesets, path objects or rules for both `ignore` and `patch` as shown below. In these cases, the policy file will now default to `{}` or `[]` internally.
**Missing Ruleset**
- results in an empty rule set with no path objects
```
ignore:
```
**Missing Path Object**
- results in an empty path object with no rules
```
ignore:
SNYK-CC-K8S-44:
```
**Missing Rule**
- all fields are optional, so this is a valid rule
```
ignore:
SNYK-CC-K8S-44:
- 'infrastructure/iac/testdata/RBAC-copy.yaml > [DocId: 1] > clusterrole > rules[0] > verbs':
```
=> fix: handle empty rules

lib/parser/v1.ts, test/unit/old-format.test.ts
Re-enables throwing of errors when an early alpha format of the `.snyk` file is found. This was temporarily commented out during the switch to Typescript, but was not re-enabled.
=> fix: check for old alpha `.snyk` file format and throw

.gitignore, lib/filter/index.ts, lib/filter/notes.ts, lib/types.ts
The vulnerability object is mutated when filtering, so this PR update the vulns type and the return type to take this into account.
After reviewing policy lib usage in the Snyk CLI, isUpgradable, upgradePath, isPatchable and patches have also been made optional
=> chore: type filter to reflect mutation

tsconfig.json
The cli has several tests defined using a tool called tap. For
reasons unknown, tap sees use of the ?? operator as invalid syntax.
Using the es2019 target leads the transpiler to use a different final
js form that tap seems to work well with.
=> fix: changes compilation target to work with snyk's cli

.circleci/config.yml
We're pinning the `semantic-release` version to `22.0.0` for the `node18` support. 
Dropping EOL `node16`.
=> chore: pin semantic-release version for node 18 support

.circleci/config.yml
This commit replaces narwhal-policy CI context which contained the expired GH_TOKEN with the nodejs-lib-release CI context which has an active GH token.
=> fix(ignr-729): replace context with expired GH token
