lib/filter/ignore.js
lib/filter/index.js
lib/filter/patch.js
test/fixtures/filter-and-track/.snyk
test/fixtures/filter-and-track/package.json
test/fixtures/filter-and-track/parsed.json
test/fixtures/filter-and-track/vulns.json
test/functional/SC-1026.test.js
test/unit/filter-ignore.test.js

Adds the ability to *see* what was removed from the vulnerabilities based on whether it was patched or ignored in the policy.
See SC-1026.test.js
Currently the snyk.io web site doesn't have any indication as to whether a vulnerability is ignored via the policy or not. This will offer visibility.
SC-1026

feat: track filtered vulns

---

.travis.yml
travis_after_all.py

- Stop testing on Node.js 0.10
- After-success script is part of repo and not fetched from GH gist for completeness and security

chore: travis settings update

---

lib/filter/ignore.js
lib/filter/patch.js
test/unit/filter-patch.test.js

Similar to ignores, patched issues will now include the path that matched when filtered.
```javascript
tap test/unit/filter-patch.test.js
```

feat: return path for patched issues

---

lib/filter/ignore.js
lib/filter/notes.js
test/fixtures/ignore-expired-no-quotes/.snyk
test/fixtures/ignore-expired-no-quotes/package.json
test/fixtures/ignore-expired-no-quotes/vulns.json
test/unit/filter-expired.test.js

Fixes https://github.com/snyk/snyk/issues/120
See https://github.com/snyk/snyk/issues/120
I didn't add any tests for the notes part - there weren't any that deal with expired notes to start with. I suspect that code might be unreachable, because these deps should be filtered out during load time? I can revisit later, unless someone gets to it sooner...

fix: convert Date automatically created from YAML into a string

---

lib/index.js
package.json
test/functional/append.test.js
test/functional/load-policies.test.js
test/unit/filter-expired.test.js
test/unit/filter-ignore.test.js
test/unit/filter-notes.test.js
test/unit/filter-patch.test.js
test/unit/filter.test.js
test/unit/policy-parse.test.js
test/unit/policy-save.test.js

Updating dependencies as node 4 is the minimal supported version now across the codebase.

fix: update deps

---

lib/parser/v1.js
test/fixtures/issues/BST-264/missing-path-to-package.snyk
test/functional/load-policies.test.js

Ignore patch if it's broken for one of vulns.
New test fixture.
This is file which cause a problem: https://github.com/guypod/java-goof/blob/master/todolist-web-struts/.snyk
And also a lot of forks of this sample project.
https://snyksec.atlassian.net/browse/BST-264

fix: ignore broken patch

---

.travis.yml
package.json

* `semver` to `^6.0.0` to catch up with newer releases
* `js-yaml` to `^3.13.0` to force a non-vuln dep

fix: bump deps

---

package.json

Fixes https://app.snyk.io/vuln/SNYK-JS-JSYAML-174129

fix: bump js-yaml to fix a vulnerability

---

.circleci/config.yml

Changing npmjs user to fix semantic release in CI/CD

chore: use different npmjs user for circle

---

.circleci/config.yml
README.md

fix: prettier readme

---

.commitlintrc.json
package.json

fix: add commit linter; change linter script

---

.circleci/config.yml

Adds fix to Circle config to start publishing release to npmjs

fix: circle release to npmjs

---

.circleci/config.yml
package.json

Add test runs for different node versions in circle

fix: test in circle in front of multiple node versions

---

.circleci/config.yml

Updating circle release workflow

fix: update circle workflows

---

.circleci/config.yml
package.json

Fixing semantic-release config to publish to both GH and NPMJS

fix: make semantic release publish to gh and npmjs

---

package.json

Use newest version of try-require

chore: update try-require

---

.github/CODEOWNERS

- Updates the `CODEOWNERS` from `@snyk/governance` to `@snyk/narwhal`

chore: rename @snyk/governance to @snyk/narwhal

---

.circleci/config.yml

Updates CircleCI config to perform OpenSource and Code scans on PRs, as well as adaily recurring tests that push the results to Snyk.
Note: Code do not currently support reporting results
[Jira NARW-1307](https://snyksec.atlassian.net/browse/NARW-1307)

chore: Snyk scan

---

lib/filter/get-vuln-source.ts
lib/filter/ignore.ts
lib/filter/index.ts
lib/filter/notes.ts
lib/filter/patch.ts
lib/types.ts

Extend typing to cover the filter package. This PR should not change any logic
[NARW-2131](https://snyksec.atlassian.net/browse/NARW-2131)
[NARW-2131]: https://snyksec.atlassian.net/browse/NARW-2131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: type filter

---

lib/index.ts
lib/parser/add-comments.ts
lib/parser/demunge.ts
lib/parser/index.ts
lib/parser/v1.ts
lib/types.ts

Extend typing to cover the parser package. This PR should not change any logic
[NARW-2131](https://snyksec.atlassian.net/browse/NARW-2131)
[NARW-2131]: https://snyksec.atlassian.net/browse/NARW-2131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: type parser

---

lib/add-exclude.ts
lib/add.ts
lib/filter/get-vuln-source.ts
lib/filter/ignore.ts
lib/filter/index.ts
lib/filter/notes.ts
lib/filter/patch.ts
lib/index.ts
lib/match.ts
lib/parser/add-comments.ts
lib/parser/demunge.ts
lib/parser/index.ts
lib/types.ts
test/unit/add-exclude.test.ts
test/unit/add.test.ts
test/unit/filter-ignore.test.ts

Further type the library in preparation for turning strict type checking on. This PR should not change any logic
[NARW-2131](https://snyksec.atlassian.net/browse/NARW-2131)
[NARW-2131]: https://snyksec.atlassian.net/browse/NARW-2131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: type library for strict type checking

---

lib/filter/ignore.ts
test/unit/filter-ignore.test.ts

fix: make ignore filter case insensitive

---

.github/CODEOWNERS

Update ownership to @snyk/ignores 
https://snyksec.atlassian.net/browse/IGNR-125

fix: IGNR-125 update ownership

---

.circleci/config.yml
catalog-info.yaml

Use the `appsecex_ignores` context in the CICD pipeline to send the data to the `appsecex_ignores` Snyk on Snyk organisation.

chore: update sos org [PRODSEC-1769]

---

lib/filter/get-vuln-source.ts
lib/filter/ignore.ts
lib/filter/index.ts
lib/filter/notes.ts
lib/filter/patch.ts
lib/match.ts
lib/policy.ts
test/unit/filter-patch.test.ts

fix: remove debug output
debug output was ending up in stdout of the CLI when running scans. This commit removes debug output to hotfix the issue. A RCA and subsequent revert & fix would be advisable after hotfixing

fix: remove debug output

---

package.json

This pull request updates the `snyk-module `library to include [this fix](https://github.com/snyk/module/pull/27) that ensures all debug logs are directed to stderr.

fix: update snyk-module library
